%% Exact linearization of the Simulink model Q1_simulink
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.9 and Simulink Control Design (TM) 5.6.
%
% Generated on: 05-Feb-2021 13:06:48

%% Specify the model name
model = 'Q1_simulink';

%% Specify the analysis I/Os
% Get the analysis I/Os from the model
io = getlinio(model);

%% Specify the operating point
% Use the model initial condition
op = operpoint(model);


%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
stepinfo(2*sys)
step(2*sys)

